# Generated by Django 4.0 on 2021-12-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_shoping_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoping',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
